In [5]:
# Dependencies
from bs4 import BeautifulSoup
import requests
import pandas as pd
import re

In [7]:
#Testing
scrape_link = 'https://www.apartments.com/apartments/ca/'

response = requests.get(scrape_link)
response
soup = BeautifulSoup(response.text, 'html.parser')
result = soup.find_all('div', class_="placardContainer")
result

ConnectionError: ('Connection aborted.', OSError("(10060, 'WSAETIMEDOUT')",))

In [ ]:
#Set up list to hold response info
link_dict = []
all_property = []

In [1]:
scrape_link = 'https://www.apartments.com/apartments/ca/{}'
# Loop through x pages of the website with filter of Single House
for scrape_links in [scrape_link.format(page) for page in range(1,3)]:
    res = requests.get(scrape_links)
    new_soup = BeautifulSoup(res.text, 'html.parser')
    new_results = new_soup.find_all('article', class_="placard")
    
    # Loop through returned results
    for result in new_results:
        find_tag = result.find('a')['href']
        link_dict.append(find_tag)

for property_link in link_dict:
    res = requests.get(property_link)
    new_soup = BeautifulSoup(res.text, 'html.parser')
    new_results = new_soup.find_all('div', class_="mainWrapper")
    
    
    for result in new_results:
        try:
            # Identify and return property name of Rental Place
            property_name = result.find('h1', class_="propertyName")
            # Identify and return address information of Rental Place
            clean_property_name = property_name.text.strip().replace("\n", "")
            street_data = result.find('div', class_="propertyAddress")
            street = street_data.text.strip().replace("\n", "").replace("\r", "")
            street_address = street.split(",")
            city = " ".join(street_address[1].split())
            state = " ".join(street_address[2].split())[:2]
            zip_code = " ".join(street_address[2].split())[2:7]
            # Identify and return number of bedroom and price of Rental Place
            bedroom_container = result.find('div', class_="rentRollupContainer")
            all_the_rents = bedroom_container.findAll('span', class_="rentRollup")
            
            bedroom_info = []
            for rent_block in all_the_rents:
                
                bedroom_type = rent_block.find('span', class_="longText").text
                try:
                    price = re.search('\$.* ', rent_block.text)
                    price = price.group(0)[:-2]
                except:
                    price = ""
                
                bedroom_info.append({
                    'bedroom_type': bedroom_type,
                    'price': price
                })
            
            rent_obj = {
                "Property_Name_Rent": clean_property_name,
                "City_Rent": city,
                "Type": "Apartment",
                "State_Rent": state,
                "Zip_code": zip_code,
                "Bedroom_Info": bedroom_info,
                
            }
            
            for item in bedroom_info:
                rent_obj[item["bedroom_type"]] = item["price"]
                

        
            all_property.append(rent_obj)
        except AttributeError as e:
            print(e)

# print(all_property)

NameError: name 'requests' is not defined

In [58]:
house_data = pd.DataFrame(all_property)
house_data

,1 Bedroom – 2 Bedrooms,1 Bedroom – 3 Bedrooms,Studio,Studio – 3 Bedrooms,1 Bedroom,2 Bedrooms,3 Bedrooms,4 Bedrooms,Bedroom_Info,City_Rent,Property_Name_Rent,State_Rent,Studio,Type,Zip_code
0,NaN,NaN,NaN,NaN,"$2,356","$2,890",NaN,NaN,"[{'bedroom_type': 'Studio', 'price': '$2,030 '...",Los Angeles,Sakura Crossing,CA,"$2,030",Apartment,90012
1,NaN,NaN,NaN,NaN,"$1,849","$2,379","$3,424",NaN,"[{'bedroom_type': 'Studio', 'price': '$1,669 '...",Costa Mesa,27 Seventy Five Mesa Verde,CA,"$1,669",Apartment,92626
2,NaN,NaN,NaN,NaN,"$3,300",,,NaN,"[{'bedroom_type': 'Studio', 'price': ''}, {'be...",Berkeley,Parker,CA,,Apartment,94704
3,NaN,NaN,NaN,NaN,"$3,215","$3,800","$5,355",NaN,"[{'bedroom_type': 'Studio', 'price': ''}, {'be...",West Hollywood,Avalon West Hollywood,CA,,Apartment,90046
4,NaN,NaN,NaN,NaN,"$2,180","$3,070",,NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$2,18...",Woodland Hills,Motif,CA,NaN,Apartment,91367
5,NaN,NaN,NaN,NaN,"$1,400","$1,805",,NaN,"[{'bedroom_type': 'Studio', 'price': ''}, {'be...",La Mesa,The Hills At Spring Street Apartments,CA,,Apartment,91941
6,NaN,NaN,NaN,NaN,"$2,655","$2,860","$4,080",NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$2,65...",Fremont,Avalon Fremont,CA,NaN,Apartment,94538
7,NaN,NaN,NaN,NaN,"$2,639","$3,765",NaN,NaN,"[{'bedroom_type': 'Studio', 'price': '$2,405 '...",Mountain View,eaves Mt. View at Middlefield,CA,"$2,405",Apartment,94043
8,NaN,NaN,NaN,NaN,,"$1,425",,NaN,"[{'bedroom_type': '1 Bedroom', 'price': ''}, {...",Ontario,Mission Village,CA,NaN,Apartment,91762
9,NaN,NaN,NaN,NaN,"$2,165","$2,745",NaN,NaN,"[{'bedroom_type': 'Studio', 'price': '$1,950 '...",Irvine,Park Place Apartment Homes,CA,"$1,950",Apartment,92612
10,NaN,NaN,NaN,NaN,"$2,015","$2,700","$3,670",NaN,"[{'bedroom_type': 'Studio', 'price': ''}, {'be...",Huntington Beach,Luce,CA,,Apartment,92647
11,NaN,NaN,NaN,NaN,"$1,425","$1,570",NaN,NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$1,42...",Vista,Sycamore Ridge Apartments,CA,NaN,Apartment,92081
12,NaN,NaN,NaN,NaN,"$2,725","$3,647","$5,583",NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$2,72...",Santa Monica,AO Santa Monica,CA,NaN,Apartment,90404
13,NaN,NaN,NaN,NaN,"$1,382","$1,502",NaN,NaN,"[{'bedroom_type': 'Studio', 'price': '$1,375 '...",Redlands,Redlands Lawn and Tennis,CA,"$1,375",Apartment,92373
14,NaN,NaN,NaN,NaN,"$3,760","$4,625",NaN,NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$3,76...",Playa Vista,Villas at Playa Vista - Montecito,CA,NaN,Apartment,90094
15,NaN,NaN,NaN,NaN,"$1,592","$2,319",NaN,NaN,"[{'bedroom_type': 'Studio', 'price': '$1,542 '...",Anaheim,The Mix at CTR City,CA,"$1,542",Apartment,92805
16,NaN,NaN,NaN,NaN,"$3,259","$3,519","$5,959",NaN,"[{'bedroom_type': 'Studio', 'price': '$3,430 '...",Redwood City,Indigo Apartment Homes,CA,"$3,430",Apartment,94063
17,NaN,NaN,NaN,NaN,"$1,897","$2,696",NaN,NaN,"[{'bedroom_type': 'Studio', 'price': ''}, {'be...",Aliso Viejo,Vantis,CA,,Apartment,92656
18,NaN,NaN,NaN,NaN,"$1,985","$2,520","$2,826","$3,154","[{'bedroom_type': '1 Bedroom', 'price': '$1,98...",Rancho Cucamonga,The Enclave at Homecoming Terra Vista,CA,NaN,Apartment,91730
19,NaN,NaN,NaN,NaN,"$2,718","$3,541",,NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$2,71...",San Jose,Avalon on the Alameda,CA,NaN,Apartment,95126
20,NaN,NaN,NaN,NaN,"$2,240","$2,905","$3,360",NaN,"[{'bedroom_type': 'Studio', 'price': '$1,905 '...",San Diego,Pacific Ridge,CA,"$1,905",Apartment,92110
21,NaN,NaN,NaN,NaN,"$3,410","$4,153",NaN,NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$3,41...",Sunnyvale,Loft House,CA,NaN,Apartment,94086
22,NaN,NaN,NaN,NaN,"$1,925","$1,997",NaN,NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$1,92...",Santa Ana,The Californian Apartments-South Coast Metro,CA,NaN,Apartment,92707
23,NaN,NaN,NaN,NaN,"$2,735","$3,330",,NaN,"[{'bedroom_type': 'Studio', 'price': '$2,590 '...",San Jose,Crescent Village Apartment Homes,CA,"$2,590",Apartment,95134
24,NaN,NaN,NaN,NaN,"$2,525","$3,318",NaN,NaN,"[{'bedroom_type': 'Studio', 'price': '$2,000 '...",Los Angeles,Next on Sixth,CA,"$2,000",Apartment,90005
25,NaN,NaN,NaN,NaN,"$1,584","$2,058",NaN,NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$1,58...",Corona,One11,CA,NaN,Apartment,92880
26,NaN,NaN,NaN,NaN,"$2,060","$2,795",NaN,NaN,"[{'bedroom_type': 'Studio', 'price': '$1,825 '...",San Diego,IDEA1,CA,"$1,825",Apartment,92101
27,NaN,NaN,NaN,NaN,"$2,284","$2,874",NaN,NaN,"[{'bedroom_type': 'Studio', 'price': '$2,309 '...",Cerritos,Sage at Cerritos,CA,"$2,309",Apartment,90703
28,NaN,NaN,NaN,NaN,NaN,"$2,030","$2,415",NaN,"[{'bedroom_type': '2 Bedrooms', 'price': '$2,0...",Ontario,Paseos at Ontario,CA,NaN,Apartment,91764
29,NaN,NaN,NaN,NaN,"$1,938","$2,511","$3,339",NaN,"[{'bedroom_type': 'Studio', 'price': '$1,849 '...",San Diego,Hanover Mission Gorge,CA,"$1,849",Apartment,92120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,NaN,NaN,NaN,NaN,"$2,570","$3,360","$6,024",NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$2,57...",Los Angeles,Palazzo East,CA,NaN,Apartment,90036
96,NaN,NaN,NaN,NaN,"$1,796","$2,557",NaN,NaN,"[{'bedroom_type': 'Studio', 'price': '$1,741 '...",Irvine,Sofi Irvine,CA,"$1,741",Apartment,92614
97,NaN,NaN,NaN,NaN,"$1,310","$1,380",NaN,NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$1,31...",Fair Oaks,Eclipse 96 Apartments,CA,NaN,Apartment,95628
98,NaN,NaN,NaN,NaN,"$2,695","$3,429",,NaN,"[{'bedroom_type': 'Studio', 'price': '$2,130 '...",Los Angeles,The 5550,CA,"$2,130",Apartment,90028
99,NaN,NaN,NaN,NaN,"$1,670","$2,040",NaN,NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$1,67...",Santa Ana,Artists Village,CA,NaN,Apartment,92701
100,NaN,NaN,NaN,NaN,"$2,832","$3,246","$4,288",NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$2,83...",San Jose,Vista 99,CA,NaN,Apartment,95134
101,NaN,NaN,NaN,NaN,"$2,390","$2,945","$3,924",NaN,"[{'bedroom_type': 'Studio', 'price': ''}, {'be...",Dublin,Avalon Dublin Station,CA,,Apartment,94568
102,NaN,NaN,NaN,NaN,"$2,430","$3,220",NaN,NaN,"[{'bedroom_type': 'Studio', 'price': '$2,075 '...",San Diego,Alexan ALX,CA,"$2,075",Apartment,92101
103,NaN,NaN,NaN,NaN,"$2,625","$3,400",NaN,NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$2,62...",Milpitas,Capitol 650,CA,NaN,Apartment,95035
104,NaN,NaN,NaN,NaN,"$2,500","$3,430",NaN,NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$2,50...",Los Angeles,Villas at Park La Brea Apartments,CA,NaN,Apartment,90036
105,NaN,NaN,NaN,NaN,,,NaN,NaN,"[{'bedroom_type': '1 Bedroom', 'price': ''}, {...",Santa Clara,Spring Creek Apartments,CA,NaN,Apartment,95051
106,NaN,NaN,NaN,NaN,"$1,740","$2,045",NaN,NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$1,74...",Costa Mesa,Pinecreek Village Apartments,CA,NaN,Apartment,92626
107,NaN,NaN,NaN,NaN,"$2,320","$2,480",NaN,NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$2,32...",Sunnyvale,The Highlander,CA,NaN,Apartment,94086
108,NaN,NaN,NaN,NaN,"$2,255","$2,630","$3,684",NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$2,25...",San Diego,Valentia,CA,NaN,Apartment,92122
109,NaN,NaN,NaN,NaN,"$2,950","$3,485",,NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$2,95...",Sunnyvale,Avalon Silicon Valley,CA,NaN,Apartment,94085
110,NaN,NaN,NaN,NaN,"$2,370","$2,925","$3,460",NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$2,37...",Pleasanton,Park Hacienda,CA,NaN,Apartment,94588
111,NaN,NaN,NaN,NaN,"$1,482","$1,675","$2,235",NaN,"[{'bedroom_type': 'Studio', 'price': '$1,399 '...",Rancho Cucamonga,Terra Vista Apartments,CA,"$1,399",Apartment,91730
112,NaN,NaN,NaN,NaN,"$4,000","$7,875",NaN,NaN,"[{'bedroom_type': 'Studio', 'price': '$3,200 '...",Santa Monica,Chelsea Santa Monica,CA,"$3,200",Apartment,90401
113,NaN,NaN,NaN,NaN,"$2,267","$2,945",NaN,NaN,"[{'bedroom_type': 'Studio', 'price': '$2,361 '...",Pasadena,Avalon Del Mar Station,CA,"$2,361",Apartment,91105
114,NaN,NaN,NaN,NaN,"$2,657","$3,828","$5,143",NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$2,65...",Marina Del Rey,Tierra del Rey,CA,NaN,Apartment,90292
115,NaN,NaN,NaN,NaN,"$2,285","$3,590",,NaN,"[{'bedroom_type': 'Studio', 'price': '$1,750 '...",Los Angeles,Stoa,CA,"$1,750",Apartment,90012
116,NaN,NaN,NaN,NaN,"$2,206","$3,190",NaN,NaN,"[{'bedroom_type': 'Studio', 'price': '$2,101 '...",Glendale,Brio Apartment Homes and Villas,CA,"$2,101",Apartment,91204
117,NaN,NaN,NaN,NaN,"$2,029","$2,573",NaN,NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$2,02...",San Diego,Olympus Corsair,CA,NaN,Apartment,92123
118,NaN,NaN,NaN,NaN,"$2,864","$3,389",,NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$2,86...",San Diego,Strata,CA,NaN,Apartment,92101
119,NaN,NaN,NaN,NaN,"$2,857","$3,509",,NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$2,85...",Los Angeles,Accent,CA,NaN,Apartment,90066
120,NaN,NaN,NaN,NaN,NaN,"$2,399","$2,899",NaN,"[{'bedroom_type': '2 Bedrooms', 'price': '$2,3...",Woodland Hills,Summit at Warner Center,CA,NaN,Apartment,91367
121,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,[{'bedroom_type': ' S...,Berkeley,Varsity Berkeley,CA,NaN,Apartment,94704
122,NaN,NaN,NaN,NaN,"$2,122","$2,586","$3,500",NaN,"[{'bedroom_type': 'Studio', 'price': '$1,995 '...",Anaheim,Jefferson Platinum Triangle,CA,"$1,995",Apartment,92805
123,NaN,NaN,NaN,NaN,"$2,453","$2,820","$3,078",NaN,"[{'bedroom_type': '1 Bedroom', 'price': '$2,45...",Fremont,The Rexford,CA,NaN,Apartment,94536
124,NaN,NaN,NaN,NaN,NaN,"$2,655","$3,690",NaN,"[{'bedroom_type': '2 Bedrooms', 'price': '$2,6...",Irvine,Carlyle,CA,NaN,Apartment,92612

In [59]:
# Export file as a CSV, without the Pandas index, but with the header
house_data.to_csv("Output/Q2-2018_Apartment_Apartment_Data26.csv", index=False, header=True)